version: "3"
services:
  dealer-stat:
    container_name: duty-helper-app
    build: .
    depends_on:
      - postgresdb
    links:
      - postgresdb:postgresdb
    networks:
      - duty-helper-network
    ports:
      - "3333:8080"
    environment:
      DATABASE_URL:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:

  postgresdb:
    image: postgres:9.6
    container_name: postgres-for-duty-helper
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: duty_helper_app_db
    restart: always
    networks:
      - duty-helper-network

  redisdb:
    container_name: redis-for-duty-helper
    image: redis
    ports:
      - "6379:6379"
    networks:
      - duty-helper-network
    restart: always

networks:
  duty-helper-network:
    driver: bridge



