spring:
  profiles:
    active: @SPRING_PROFILES_ACTIVE@

  messages:
    basename: "lang/res"

  jpa:
    open-in-view: false

telegram:
  bot:
#    chat id of the bot
    admin:
    name: ${BOT_NAME:Duty Helper Bot}
    token: ${BOT_TOKEN}
